### ISSUE TITLE
using other algorithm

### ISSUE THREAD

**Issue by adamardiyanto** [sahibdhanjal/Path-Planning-Simulator#2]
hi i want to know hot to use JPS algorithm in this python simulator? or could you explain how to use other algorithm? thank you

**Comment by sahibdhanjal** [comment]
Hi, sorry I don't check my Github anymore. You might want to just directly adapt this implementation of JPS (https://github.com/sahibdhanjal/Path-Planning-Simulator/blob/master/Python%20Simulator/Frontier%20Exploration/JPS.py) for your usecase. This was originally written to work with the Turtlebot and ROS
